#!/bin/bash

[ $UID -ne 0 ] && echo "Only root can bootstrap." && exit 1

USER=mikespook
PASSWORD=false

usage() {
    echo "Usage: $0 [-k \$path] [-u \$user] [-p]"
	echo " -k Path of SSH public key"
	echo " -u User to be created"
	echo " -p Initializing password"
}

while getopts 'k:u:p' o &>> /dev/null; do
    case "$o" in
    k)
        key="$OPTARG";;
	u)
		user="$OPTARG";;
    p)
        password=true;;
    *)
        usage
		exit 3;;
    esac
done

usage
printf "\n\tSSH Pub-key:\t$key\n"
printf "\tUser name:\t$user:\n"
printf "\tInit passwd:\t$password\n\n"
echo -n "Continue to bootstrap? [y|N]: "
read answer
if [ "$answer" != "Y" ] && [ "$answer" != "y" ]; then
	exit 1
fi

apt-get update -y
apt-get dist-upgrade -y
apt-get install git wget
apt-get clean

id $user &>> /dev/null
[ $? -eq 0 ] && echo "User $user already existed." && exit 2
adduser --quiet --disabled-password --gecos "" $user
egrep -i "^admin" /etc/group
[ $? -ne 0 ] && addgroup --system admin
usermod -a -G admin $user
usermod -a -G sudo $user

home=`getent passwd "$user" | cut -d: -f6`
if [ ! -z "$key" ]; then
	mkdir -p $home/.ssh
	if [ -f $key ]; then
		cp $key $home/.ssh/authorized_keys
	else
		wget $key -O $home/.ssh/authorized_keys
	fi
	chown -R $user:$user $home/.ssh
	chmod 700 $home/.ssh
	chmod 600 $home/.ssh/authorized_keys
fi

$password && passwd $user

git clone https://github.com/mikespook/mine.git $home/.mikespook
chown -R $user:$user $home/.mikespook

sudo -u $user $home/.mikespook/setup

exit 0
