#!/bin/bash

[ $UID -ne 0 ] && echo "Only root can bootstrap." && exit 1

USER=mikespook
PASSWORD=false

usage() {
    echo "Usage: $0 [-k \$path] [-u \$user] [-p]"
	echo " -k Path of SSH public key"
	echo " -u User to be created"
	echo " -p Initializing password"
}

while getopts 'k:u:p' o &>> /dev/null; do
    case "$o" in
    k)
        KEY="$OPTARG";;
	u)
		USER="$OPTARG";;
    p)
        PASSWORD=true;;
    *)
        usage
		exit 3;;
    esac
done

usage
printf "\n\tSSH Pub-key:\t$KEY\n"
printf "\tUser name:\t$USER\n"
printf "\tInit passwd:\t$PASSWORD\n\n"
echo -n "Continue to bootstrap? [y|N]: "
read answer
if [ "$answer" != "Y" ] || [ "$answer" != "y" ]; then
	exit 1
fi

apt-get update -y
apt-get dist-upgrade -y
apt-get install git wget
apt-get clean

id $USER &>> /dev/null
[ $? -eq 0 ] && echo "User $USER already existed." && exit 2
adduser --quiet --disabled-password --gecos "" $USER
egrep -i "^admin" /etc/group
[ $? -ne 0 ] && addgroup --system admin
usermod -a -G admin $USER
usermod -a -G sudo $USER

home=`getent passwd "$USER" | cut -d: -f6`
if [ ! -z "$KEY" ]; then
	mkdir -p $home/.ssh
	wget $KEY -O $HOME/.ssh/authorized_keys
	chown -R $USER:$USER $home/.ssh
	chmod 700 $home/.ssh
	chmod 600 $home/.ssh/authorized_keys
fi

$PASSWORD && passwd $USER

git clone https://github.com/mikespook/mine.git $home/.mikespook

f=$home/.bashrc
echo '. $HOME/.mikespook/bashrc ##mikespook' >> $f

d=$home/.vim/bundle
git clone https://github.com/gmarik/Vundle.vim.git $d/vundle

ln -sf $home/.mikespook/vim/vimrc $home/.vimrc
ln -sf $home/.mikespook/git $home/.git

exit 0
