#!/bin/bash

usage() {
    echo "Usage: setup"
    exit 1
}

while getopts '' o &>> /dev/null; do
    case "$o" in
    *)
        usage;;
    esac
done

f=$HOME/.bashrc
if [ -f $f ]; then
	sed -i -e '/##mikespook/d' $f
fi
echo '. $HOME/.mikespook/bashrc ##mikespook' >> $f

ln -sf $HOME/.mikespook/vim/vimrc $HOME/.vimrc
ln -sf $HOME/.mikespook/git $HOME/.git
