#!/bin/bash

usage() {
    echo "Usage: setup"
    exit 1
}

while getopts '' o &>> /dev/null; do
    case "$o" in
    *)
        usage;;
    esac
done

f=$HOME/.bashrc
sed -i -e '/##mikespook/d' $f
echo '. $HOME/.mikespook/bashrc ##mikespook' >> $f
