#!/usr/bin/env bash

usage() {
    echo "Usage: setup [\$home]"
    exit 1
}

while getopts '' o &>> /dev/null; do
    case "$o" in
    *)
        usage;;
    esac
done

home=$1
[ -z $1 ] && home=$HOME

f=$home/.bashrc
if [ -f $f ]; then
	sed -i -e '/##mikespook/d' $f
fi
echo '. $HOME/.mikespook/bashrc ##mikespook' >> $f

d=$home/.vim/bundle
git clone https://github.com/gmarik/Vundle.vim.git $d/vundle

ln -sf $home/.mikespook/vim/vimrc $home/.vimrc
ln -sf $home/.mikespook/git $home/.git
