if filereadable(expand("~/.mikespook/vim/vimrc.before"))
        source ~/.mikespook/vim/vimrc.before
endif

if filereadable(expand("~/.vimrc.before.local"))
        source ~/.vimrc.before.local
endif

if filereadable(expand("~/.mikespook/vim/vimrc.config"))
        source ~/.mikespook/vim/vimrc.config
endif

if filereadable(expand("~/.vimrc.local"))
        source ~/.vimrc.local
endif
