#!/bin/bash
base=$HOME/.mikespook/
. $base/lib/funcs.sh
if [ "$(ls -A $base/conf-enabled)" ]; then
	for f in $base/conf-enabled/*; do
		. $f
	done
fi
export PATH=$PATH:$base/bin
export PS1=$(__mikespook_ps1)
