#!/bin/bash
export GOROOT=$HOME/golang/go
export GOROOT_BOOTSTRAP=$HOME/golang/go-bootstrap
export GOPATH=$HOME/golang/3rdpkg:$GOROOT:$HOME/golang/own
_ifs=$IFS
IFS=':'
for dir in $GOPATH; do
	export PATH=$PATH:$dir/bin
done
IFS=$_ifs
